## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file lin_alg.sagetex.sage
from sage.all_cmdline import *   # import sage library

_sage_const_387 = Integer(387); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_11 = Integer(11); _sage_const_14 = Integer(14); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_10 = Integer(10); _sage_const_389 = Integer(389); _sage_const_391 = Integer(391); _sage_const_0 = Integer(0)## This file (lin_alg.sagetex.sage) was *autogenerated* from lin_alg.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('lin_alg', version='2021/10/16 v3.6', version_check=True)
_st_.current_tex_line = _sage_const_387 
_st_.blockbegin()
try:
  A =  span(column_matrix([[_sage_const_1 ,_sage_const_4 ,_sage_const_5 ],[_sage_const_3 ,-_sage_const_11 ,-_sage_const_14 ], [_sage_const_2 ,_sage_const_8 ,_sage_const_10 ]]))
except:
 _st_.goboom(_sage_const_389 )
_st_.blockend()
try:
 _st_.current_tex_line = _sage_const_391 
 _st_.inline(_sage_const_0 , latex(A))
except:
 _st_.goboom(_sage_const_391 )
_st_.endofdoc()

