## -*- encoding: utf-8 -*-
## This file (lin_alg.sagetex.sage) was *autogenerated* from lin_alg.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('lin_alg', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()
